repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        stages: [commit, push]
        language: system
        entry: isort
        args: 
        -   "--length-sort"
        -   "--profile"
        -   "black"
        -   "--line-length=120"
        -   "."
        always_run: true
        pass_filenames: false

-   repo: local
    hooks:
    -   id: black
        name: black
        stages: [commit, push]
        language: system
        entry: black
        args: 
        -   "--line-length=120"
        -   "."
        -   "--diff"
        always_run: true
        pass_filenames: false

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        stages: [commit, push]
        language: system
        entry: mypy
        args: 
        -   "--check-untyped-defs"
        -   "--config-file=.github/mypy/mypy.ini"
        -   "floss/"
        -   "scripts/"
        -   "tests/"
        always_run: true
        pass_filenames: false

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        stages: []
        language: system
        pass_filenames: false
        always_run: true
        entry: pytest
        args:
        -   "--verbose"
        -   "tests/"

