name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# save workspaces to speed up testing
env:
  FLOSS_SAVE_WORKSPACE: "True"

jobs:
  code_style:
    runs-on: ubuntu-20.04
    # Pin action version by commit hash to maximize trust, ref: https://securitylab.github.com/research/github-actions-building-blocks/
    steps:
    - name: Checkout FLOSS
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up Python 3.8
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .[dev]
    - name: Lint with isort
      run: pre-commit run isort
    - name: Lint with black
      run: pre-commit run black
    - name: Check types with mypy
      run: pre-commit run mypy

  tests:
    name: Tests in ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-13]
        # across all operating systems
        # version numbers are strings, not floats
        python-version: ['3.8', '3.11']
        include:
          # on Ubuntu run these as well
          - os: ubuntu-20.04
            python-version: '3.9'
          - os: ubuntu-20.04
            python-version: '3.10'
    steps:
    - name: Checkout FLOSS with submodule
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pyyaml
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get install -y libyaml-dev
    - name: Install FLOSS
      run: |
        pip install -r requirements.txt
        pip install -e .[dev]
    - name: Run tests
      run: pytest tests/
